### ISSUE TITLE
Publish in ABAPGit

### ISSUE THREAD

**Issue by PeregrinTooc** [lucastetreault/ABAPSlim#2]
Hi Lucas, 

this is great, I feared I would need to do this completely by myself :) Are you still using it?

I would be very interested in using it and also provide more functionality. However, can we get the source code in the ABAPGit format instead of the SAPlink nuggets? That would make both installing and contributing easier :)

Kind regards,
Philipp

**Comment by lucastetreault** [comment]
Hi Philipp, unfortunately I haven't touched an SAP system in almost 5 years! If you'd like to continue work on this I would suggest you fork the repo 👍
